language: node_js

sudo: false

matrix:
  include:
    - node_js: 4
      script:
        - npm run-script lint
        - npm run-script test

node_js:
  - 5
  - 6
  - 7

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

notifications:
  email: false
